.TH pq-theta 1 "9 June 2016" "pq-genetics-v0.0.2" "Population and Quantitative Genetics Tools"
.SH NAME
pq-theta \- Calculate theta-based population genetics statistics
.SH SYNOPSIS
.PP
.B pq-theta
.RI < nsam >
.RI [ OPTIONS ]
.PP

.SH DESCRIPTION
.PP
Calculate theta-based population genetics statistics

.SH OPTIONS
.PP
.BI "-b " BOOL
    takes values 0 or 1, indicating whether theta values should be 
    give per base pair or summed over the entire region. [1]
  
.BI "-f " INT
    column number (1-indexed) of the factor over which 
    the stats should be calculated. The default is to output 
    stats per chromosome, but the fourth name column could 
    be used instead to calculate over some group of features. [1]


.SH Author
.PP
Michael Stocks
