.TH pqgen-theta 1

.SH NAME
pqgen-theta \- Calculate site frequency based statistics.

.SH SYNOPSIS
.PP
.B pqgen theta
.RI [ OPTIONS ]
.RI [ FILE ]

.SH DESCRIPTION
.PP
Calculate site frequency based statistics.

.SH OPTIONS

.TP
.B -b \fINUM\fR

.R Toggle whether to calculate theta estimates per bp or across entire region (1 by default).

.SH Author
.PP
Michael Stocks
