.TH pq-dna2codon 1 "9 June 2016" "pq-genetics-v0.0.2" "Population and Quantitative Genetics Tools"
.SH NAME
pq-dna2codon \- Combine nucleotide sequences into codons
.SH SYNOPSIS
.PP
.B pqgen
.RI dna2codon
.PP

.SH DESCRIPTION
.PP
Combine nucleotide sequences into codons

.SH OPTIONS

.SH Author
.PP
Michael Stocks
