.TH pq-genetics 1 "9 June 2016" "pq-genetics-v0.0.2" "Population and Quantitative Genetics Tools"
.SH NAME
pq-genetics \- Population and Quantitative Genetics Tools
.SH SYNOPSIS
.PP
.B pqgen
.RI < command >
.RI [ OPTIONS ]
.PP
.BI pq-< command >
.RI [ OPTIONS ]

.SH DESCRIPTION
.PP
Population and Quantitative Genetics Tools

.SH COMMANDS

.TP 10 \"------ pq-dna2codon
.B pq-dna2codon(1)
.B Combine nucleotide sequences into codons

.TP 10 \"------ pq-theta
.B pq-theta(1)
.B Calculate theta-based population genetics statistics

.SH Author
.PP
Michael Stocks
