.TH pq-theta 1 "9 June 2016" "pq-genetics-v0.0.2" "Population and Quantitative Genetics Tools"
.SH NAME
pq-theta \- Calculate theta-based population genetics statistics
.SH SYNOPSIS
.PP
.B pqgen
.RI theta
.RI < nsam >
.RI [< fcol >]
.PP

.SH DESCRIPTION
.PP
Calculate theta-based population genetics statistics

.SH OPTIONS

.SH Author
.PP
Michael Stocks
